# GET http://localhost:3000/api/album

# GET single album
# GET http://localhost:3000/api/album/4

# GET artist
# GET http://localhost:3000/api/artist

# GET artist sorted by first name
# GET http://localhost:3000/api/artist/sort/fName

# GET single artist
# GET http://localhost:3000/api/artist/3

# GET band
# GET http://localhost:3000/api/band/

# GET band sorted by band id
# GET http://localhost:3000/api/band/band_id

# GET single band
# GET http://localhost:3000/api/band/5

# GET label
# GET http://localhost:3000/api/label

# GET label sorted by label id
#  GET http://localhost:3000/api/label/sort/label_id

# GET single label
#  GET http://localhost:300/api/label/4

# GET http://localhost:3000/api/album/get_albums/3

# 
# POST http://localhost:3000/api/artist/create
# Content-Type: application/json
# {
#     "fName": "michael",
#     "lName": "jackson"
# }